import {
  Box,
  Building2,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleDot,
  Cog,
  FileText,
  Home,
  LayoutDashboard,
  LogOut,
  Moon,
  Package,
  Plus,
  RotateCcw,
  Search,
  Settings,
  Sun,
  User,
  Users,
  AlertTriangle,
  X,
  ArrowRight,
  Clock,
  Wrench,
  AlertCircle,
  Loader2,
  Menu,
  Pencil,
  Undo2,
  Eye,
  EyeOff,
  Trash2,
  Table,
  LayoutGrid,
} from "lucide-react"

export const Icons = {
  box: Box,
  building: Building2,
  check: CheckCircle2,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  circleDot: CircleDot,
  cog: Cog,
  file: FileText,
  home: Home,
  dashboard: LayoutDashboard,
  logout: LogOut,
  moon: Moon,
  package: Package,
  plus: Plus,
  return: RotateCcw,
  search: Search,
  settings: Settings,
  sun: Sun,
  user: User,
  users: Users,
  warning: AlertTriangle,
  x: X,
  close: X,
  arrow: ArrowRight,
  clock: Clock,
  wrench: Wrench,
  alert: AlertCircle,
  loader: Loader2,
  menu: Menu,
  edit: Pencil,
  returnPart: Undo2,
  eye: Eye,
  eyeOff: EyeOff,
  trash: Trash2,
  table: Table,
  layout: LayoutGrid,
}

export type IconName = keyof typeof Icons
